services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "9696:9696"
    environment:
      - PREDICTION_NAME=UK_house_price
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MODEL_LOCATION=/app/model
      - TEST_RUN=True
      - REGION=${REGION}
      - RUN_ID=${RUN_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    volumes:
      - "./model:/app/model"
