datasets:
  uk_house_price:
    column_mapping:
      numerical_features:
        - 'Average_Price'
        - 'y'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - data_quality
    reference_file: ./datasets/Average_price-2022-06_from1995.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
